### ISSUE TITLE
Possible to use this as a client SDK?

### ISSUE THREAD

**Issue by evelant** [mrbandler/FsFirestore#3]
I'm toying with building a user facing app with Godot and F#. I'd like to use firebase and this library looks great but it connects as an admin via a service account which obviously isn't OK as part of a client app/game. Would it be possible to authenticate as a normal firestore end user? My understanding is that this isn't possible when using the service account connection method.

**Comment by mrbandler** [comment]
Hi @AndrewMorsillo,

I am not sure if this is possible, as FsFirestore is just a somewhat functional wrapper around the C# lib provided by Google, and the C# lib (to my current knowledge) was only meant to run on servers. Although, this could have changed as the lib was in beta state when I originally implemented FsFirestore. But I will check and implement it with the next maintenance release.

Godot & F#, this sounds like an interesting project. What are you trying to create, if you don't mind me asking? 🤔

**Comment by evelant** [comment]
I've been building a gamified productivity app in React Native + Firebase and the game-y parts of it are extremely painful on that platform. RN is really difficult when it comes to animation plus some other issues such as web support being difficult or not easily compatible. 

I'm investigating Godot as an alternative. It looks pretty attractive as an app platform, not just games. It runs everywhere including web and desktop. It has an excellent UI framework  (no css!), the Godot editor is a Godot app. Somebody in the community recently built a Trello clone with little difficulty. It has .net support on all platforms. Being a game engine it has excellent tools for smooth 2d animation. It really seems like it could be a better cross platform app framework than the likes of RN, Xamarin, Flutter, etc. So I'm toying around with it for those reasons =). I'm using F# just because, it works more or less seamlessly with Godot and I want to spend more time in functional languages the more I work with Typescript every day haha.

**Comment by mrbandler** [comment]
Hi @AndrewMorsillo,

sorry, it has been a while.
Very interesting project indeed!

I just moved FsFirestore to GitHub Actions and created the maintenance release. Sadly I found no way to use the lib as a client-facing utility. I tried some dirty tricks but the underlaying C# lib was never satisfied.

My recommendation would be to either create Firebase Functions to act like a CRUD API or use [GCP Cloud Run](https://cloud.google.com/run) for a serverless CRUD API which you could write in F# and with FsFirestore. The latter was my approach for the project I wrote FsFirestore for.

I hope you project will be a success, even without FsFirestore 😅.

Regards,
Michael
